"""tyFlow operator catalog: full operator type-name list from the official docs.

Source: https://docs.tyflow.com/tyflow_operators/ (fetched 2026-07-20, tyFlow 2.x).
Names are addOperator type strings exactly as titled in the docs. Availability on
a given installation is probed by `harvest_tyflow_manifest` — Pro-only or
version-gated operators simply probe as unavailable.
"""

from __future__ import annotations

TYFLOW_OPERATOR_NAMES: tuple[str, ...] = (
    "Birth",
    "Birth Burst",
    "Birth Flow",
    "Birth Fluid",
    "Birth ForestPack",
    "Birth Intersections",
    "Birth Objects",
    "Birth PRT",
    "Birth Paint",
    "Birth Skeleton",
    "Birth Spline",
    "Birth Surface",
    "Birth Voxels",
    "Array",
    "Branch",
    "Grow",
    "Resample",
    "Spawn",
    "Delete",
    "Boundary",
    "Cluster Force",
    "Flock",
    "Flow Update",
    "Fluid Force",
    "Force",
    "Hair Bind",
    "Integrate",
    "Limiter",
    "Mass",
    "Object Bind",
    "PRT Update",
    "Pack",
    "Particle Force",
    "Particle Groups",
    "Path Follow",
    "Point Force",
    "Position Displace",
    "Position Hair",
    "Position Icon",
    "Position Object",
    "Position Raycast",
    "Position Transfer",
    "Push In/Out",
    "Rasterize",
    "Restore",
    "Rotation",
    "Scale",
    "Slow",
    "Speed",
    "Spin",
    "Spread",
    "Stop",
    "Surface Force",
    "Cluster",
    "Custom Properties",
    "Fluid Properties",
    "Property Collect",
    "Property Transfer",
    "Script",
    "Temporal Smooth",
    "Link to Target",
    "Move to Target",
    "Set Target",
    "Instance ID",
    "Instance Material",
    "Mapping",
    "Material ID",
    "Vertex Color",
    "Boolean",
    "Displace",
    "Move Pivots",
    "Optimize",
    "Push",
    "Relax",
    "Repair",
    "Shape",
    "Shape Remove",
    "Shell",
    "Smooth",
    "Sort",
    "Subdivide",
    "Tets",
    "Weld",
    "Bounds Fracture",
    "Brick Fracture",
    "Convex Hull",
    "Edge Fracture",
    "Element Attach",
    "Element Fracture",
    "Face Fracture",
    "Fuse",
    "Multifracture",
    "Voronoi Fracture",
    "Angle Bind",
    "Cloth Bind",
    "Cloth Collect",
    "Modify Bindings",
    "Particle Bind",
    "Particle Break",
    "Particle Physics",
    "Particle Switch",
    "Wobble",
    "PhysX Bind",
    "PhysX Break",
    "PhysX Collision",
    "PhysX Fluid",
    "PhysX Modify",
    "PhysX Shape",
    "PhysX Switch",
    "Actor",
    "Actor Animation",
    "Actor Center",
    "Actor Collect",
    "Actor Convert",
    "Pathfinding",
    "Instance Node",
    "Mesh",
    "Spline Paths",
    "Collision",
    "Find Target",
    "Object Test",
    "Property Test",
    "Select",
    "Send Out",
    "Split",
    "Surface Test",
    "Time Test",
    "Particle Export",
    "Camera Cull",
    "Display",
    "Display Data",
    "Object to VDB",
    "Value",
    "Baseline",
    "Debug",
    "Global",
    "MAXScript",
    "Notes",
    "Separator",
    "Birth Inferno",
    "Inferno Bounds",
    "Inferno Collider",
    "Inferno Color",
    "Inferno Display",
    "Inferno Emitter",
    "Inferno Eraser",
    "Inferno Force",
    "Inferno Mesh Force",
    "Inferno Modify",
    "Inferno Recall",
    "Inferno Scale",
    "Inferno Spline Force",
    "Inferno Temperature",
    "Inferno Vorticity",
    "Inferno to VDB",
    "Inferno Blast",
    "Inferno Properties",
    "Inferno Spawn",
    "Inferno Connect",
    "Inferno Export",
    "Birth Terrain",
    "Object to Terrain",
    "Terrain Clear",
    "Terrain Copy Out",
    "Terrain Display",
    "Terrain Download",
    "Terrain FX",
    "Terrain Filter",
    "Terrain Liquid",
    "Terrain Mesh",
    "Terrain Noise",
    "Terrain Resample",
    "Terrain Scatter",
    "Terrain Slope",
    "Terrain Snow",
    "Terrain Tile",
    "Terrain Tools",
    "Terrain Transform",
    "Terrain Warp",
    "Texmap to Terrain",
    "Terrain Export",
    "VDB Force",
    "VDB Export",
    "Birth VDB",
    "Particles to VDB",
    "VDB Clear",
    "VDB Convert",
    "VDB Copy Out",
    "VDB Display",
    "VDB Filter",
    "VDB Merge",
    "VDB Mesh",
    "VDB Modify",
    "VDB Solver",
    "VDB Split",
    "VDB to Particles",
)

# Operators that execute arbitrary user code. Creating one (empty) is inert, but
# tools that SET script/expression content must gate on safe mode + explicit
# authorization.
EXECUTABLE_OPERATOR_NAMES: frozenset[str] = frozenset({"Script", "MAXScript"})
